In [1]:
# To work with dataframes
import pandas as pd

# To perform numerical operations
import numpy as np

# To visualize data
import seaborn as sns

# To partition the data
from sklearn.model_selection import train_test_split

# Importing the Random Forest Classifier
from sklearn.ensemble import RandomForestClassifier

# Importing performance metrics - accuracy score & confusion matrix
from sklearn.metrics import accuracy_score, confusion_matrix

In [3]:
from google.colab import files
uploaded = files.upload()


Saving income(1) (2).csv to income(1) (2).csv


In [4]:
import pandas as pd

# Replace 'filename.csv' with the actual file name
data = pd.read_csv('income(1) (2).csv', na_values=[" ?"])


In [5]:
print(data.head)

<bound method NDFrame.head of        age       JobType         EdType        maritalstatus  \
0       45       Private        HS-grad             Divorced   
1       24   Federal-gov        HS-grad        Never-married   
2       44       Private   Some-college   Married-civ-spouse   
3       27       Private            9th        Never-married   
4       20       Private   Some-college        Never-married   
...    ...           ...            ...                  ...   
31973   34     Local-gov        HS-grad        Never-married   
31974   34     Local-gov   Some-college        Never-married   
31975   23       Private   Some-college   Married-civ-spouse   
31976   42     Local-gov   Some-college   Married-civ-spouse   
31977   29       Private      Bachelors        Never-married   

             occupation     relationship    race   gender  capitalgain  \
0          Adm-clerical    Not-in-family   White   Female            0   
1          Armed-Forces        Own-child   White     

In [6]:
# Data pre-processing
# =============================================================================

data.isnull().sum()

missing = data[data.isnull().any(axis=1)]
# axis=1 => to consider at least one column value is missing in a row

In [7]:
data2 = data.dropna(axis=0)

In [8]:

# Reindexing the salary status names to 0,1
data2['SalStat'] = data2['SalStat'].map({' less than or equal to 50,000': 0, ' greater than 50,000': 1})
print(data2['SalStat'])

0        0
1        0
2        1
3        0
4        0
        ..
31973    0
31974    0
31975    0
31976    0
31977    0
Name: SalStat, Length: 30162, dtype: int64


<ipython-input-8-84a92c8cf0e8>:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data2['SalStat'] = data2['SalStat'].map({' less than or equal to 50,000': 0, ' greater than 50,000': 1})


In [9]:
new_data = pd.get_dummies(data2, drop_first=True)

In [10]:
# Storing the column names
columns_list = list(new_data.columns)
print(columns_list)

['age', 'capitalgain', 'capitalloss', 'hoursperweek', 'SalStat', 'JobType_ Local-gov', 'JobType_ Private', 'JobType_ Self-emp-inc', 'JobType_ Self-emp-not-inc', 'JobType_ State-gov', 'JobType_ Without-pay', 'EdType_ 11th', 'EdType_ 12th', 'EdType_ 1st-4th', 'EdType_ 5th-6th', 'EdType_ 7th-8th', 'EdType_ 9th', 'EdType_ Assoc-acdm', 'EdType_ Assoc-voc', 'EdType_ Bachelors', 'EdType_ Doctorate', 'EdType_ HS-grad', 'EdType_ Masters', 'EdType_ Preschool', 'EdType_ Prof-school', 'EdType_ Some-college', 'maritalstatus_ Married-AF-spouse', 'maritalstatus_ Married-civ-spouse', 'maritalstatus_ Married-spouse-absent', 'maritalstatus_ Never-married', 'maritalstatus_ Separated', 'maritalstatus_ Widowed', 'occupation_ Armed-Forces', 'occupation_ Craft-repair', 'occupation_ Exec-managerial', 'occupation_ Farming-fishing', 'occupation_ Handlers-cleaners', 'occupation_ Machine-op-inspct', 'occupation_ Other-service', 'occupation_ Priv-house-serv', 'occupation_ Prof-specialty', 'occupation_ Protective-s

In [11]:
# Separating the input names from data
features = list(set(columns_list) - set(['SalStat']))
print(features)

['occupation_ Other-service', 'nativecountry_ Jamaica', 'EdType_ Doctorate', 'JobType_ Private', 'relationship_ Own-child', 'relationship_ Other-relative', 'nativecountry_ Trinadad&Tobago', 'nativecountry_ Laos', 'maritalstatus_ Married-civ-spouse', 'nativecountry_ Hong', 'nativecountry_ China', 'EdType_ Prof-school', 'nativecountry_ Philippines', 'capitalloss', 'age', 'occupation_ Protective-serv', 'occupation_ Handlers-cleaners', 'nativecountry_ Dominican-Republic', 'race_ Black', 'occupation_ Craft-repair', 'EdType_ Preschool', 'JobType_ State-gov', 'nativecountry_ United-States', 'capitalgain', 'nativecountry_ Scotland', 'JobType_ Self-emp-not-inc', 'EdType_ 1st-4th', 'nativecountry_ Ecuador', 'maritalstatus_ Never-married', 'EdType_ 7th-8th', 'race_ Asian-Pac-Islander', 'occupation_ Tech-support', 'relationship_ Unmarried', 'race_ White', 'nativecountry_ Guatemala', 'EdType_ 11th', 'nativecountry_ Haiti', 'maritalstatus_ Widowed', 'occupation_ Exec-managerial', 'nativecountry_ Ind

In [12]:
y = new_data['SalStat'].values
print(y)

[0 0 1 ... 0 0 0]


In [13]:
x = new_data[features].values
print(x)


[[0 0 0 ... 0 1 0]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [14]:
# Splitting the data into train and test
train_x, test_x, train_y, test_y = train_test_split(x, y, test_size=0.3, random_state=0)


In [15]:
import xgboost as xgb

# Create an XGBoost classifier
xgb_classifier = xgb.XGBClassifier(n_estimators=100, max_depth=6, learning_rate=0.1, random_state=0)

# Fit the model to the training data
xgb_classifier.fit(train_x, train_y)

# Make predictions on the test data
xgb_prediction = xgb_classifier.predict(test_x)

# Calculate the accuracy score
xgb_accuracy = accuracy_score(test_y, xgb_prediction)

print("XGBoost Accuracy:", xgb_accuracy)


XGBoost Accuracy: 0.8658415294507681


In [16]:
import xgboost as xgb
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split

# Make sure x and y are correctly defined with data

# Initialize an empty list to store accuracy scores
accuracy_scores = []

# Perform XGBoost classification for 15 iterations
for i in range(20):
    # Split the data into training and testing sets (adjust sizes as needed)
    X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=i)

    # Initialize an XGBoost classifier
    xgb_model = xgb.XGBClassifier()

    # Train the model on the training data
    xgb_model.fit(X_train, y_train)

    # Make predictions on the test data
    predictions = xgb_model.predict(X_test)

    # Calculate accuracy and append to the list
    accuracy = accuracy_score(y_test, predictions)
    accuracy_scores.append(accuracy)

# Print the accuracy scores for each iteration
for i, score in enumerate(accuracy_scores):
    print(f'Iteration {i + 1} - Accuracy: {score:.2%}')


Iteration 1 - Accuracy: 86.89%
Iteration 2 - Accuracy: 86.68%
Iteration 3 - Accuracy: 87.06%
Iteration 4 - Accuracy: 87.02%
Iteration 5 - Accuracy: 86.94%
Iteration 6 - Accuracy: 86.83%
Iteration 7 - Accuracy: 87.00%
Iteration 8 - Accuracy: 87.23%
Iteration 9 - Accuracy: 86.26%
Iteration 10 - Accuracy: 86.64%
Iteration 11 - Accuracy: 86.83%
Iteration 12 - Accuracy: 86.56%
Iteration 13 - Accuracy: 86.77%
Iteration 14 - Accuracy: 86.66%
Iteration 15 - Accuracy: 86.69%
Iteration 16 - Accuracy: 86.35%
Iteration 17 - Accuracy: 86.86%
Iteration 18 - Accuracy: 85.83%
Iteration 19 - Accuracy: 86.30%
Iteration 20 - Accuracy: 86.53%


In [17]:
import xgboost as xgb
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split
import numpy as np

# Make sure x and y are correctly defined with data

# Initialize empty lists to store accuracy scores and losses
accuracy_scores = []
losses = []  # Define a list to store your custom loss values

# Perform XGBoost classification for 20 iterations
for i in range(20):
    # Split the data into training and testing sets (adjust sizes as needed)
    X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=i)

    # Initialize an XGBoost classifier
    xgb_model = xgb.XGBClassifier()

    # Train the model on the training data
    xgb_model.fit(X_train, y_train)

    # Make predictions on the test data
    predictions = xgb_model.predict(X_test)

    # Calculate accuracy and append to the list
    accuracy = accuracy_score(y_test, predictions)
    accuracy_scores.append(accuracy)

    # Define your custom loss function and calculate loss
    # Here's an example using mean squared error as a loss function
    # Replace this with your specific loss function
    loss = ((y_test - predictions) ** 2).mean()
    losses.append(loss)

# Print the accuracy scores and losses for each iteration
for i, (score, loss) in enumerate(zip(accuracy_scores, losses)):
    print(f'Iteration {i + 1} - Accuracy: {score:.2%} - Loss: {loss:.4f}')


Iteration 1 - Accuracy: 86.89% - Loss: 0.1311
Iteration 2 - Accuracy: 86.68% - Loss: 0.1332
Iteration 3 - Accuracy: 87.06% - Loss: 0.1294
Iteration 4 - Accuracy: 87.02% - Loss: 0.1298
Iteration 5 - Accuracy: 86.94% - Loss: 0.1306
Iteration 6 - Accuracy: 86.83% - Loss: 0.1317
Iteration 7 - Accuracy: 87.00% - Loss: 0.1300
Iteration 8 - Accuracy: 87.23% - Loss: 0.1277
Iteration 9 - Accuracy: 86.26% - Loss: 0.1374
Iteration 10 - Accuracy: 86.64% - Loss: 0.1336
Iteration 11 - Accuracy: 86.83% - Loss: 0.1317
Iteration 12 - Accuracy: 86.56% - Loss: 0.1344
Iteration 13 - Accuracy: 86.77% - Loss: 0.1323
Iteration 14 - Accuracy: 86.66% - Loss: 0.1334
Iteration 15 - Accuracy: 86.69% - Loss: 0.1331
Iteration 16 - Accuracy: 86.35% - Loss: 0.1365
Iteration 17 - Accuracy: 86.86% - Loss: 0.1314
Iteration 18 - Accuracy: 85.83% - Loss: 0.1417
Iteration 19 - Accuracy: 86.30% - Loss: 0.1370
Iteration 20 - Accuracy: 86.53% - Loss: 0.1347


In [18]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

# Create a Decision Tree classifier
dt_classifier = DecisionTreeClassifier(random_state=0)  # You can adjust hyperparameters as needed

# Fit the model to the training data
dt_classifier.fit(train_x, train_y)

# Make predictions on the test data
dt_prediction = dt_classifier.predict(test_x)

# Calculate the accuracy score
dt_accuracy = accuracy_score(test_y, dt_prediction)

print("Decision Tree Accuracy:", dt_accuracy)


Decision Tree Accuracy: 0.8085976350978009


In [19]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split

# Make sure x and y are correctly defined with data

# Initialize empty lists to store accuracy scores and losses
accuracy_scores = []
losses = []  # Define a list to store your custom loss values

# Perform Decision Tree classification for 20 iterations
for i in range(20):
    # Split the data into training and testing sets (adjust sizes as needed)
    X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=i)

    # Initialize a Decision Tree classifier
    dt_model = DecisionTreeClassifier()

    # Train the model on the training data
    dt_model.fit(X_train, y_train)

    # Make predictions on the test data
    predictions = dt_model.predict(X_test)

    # Calculate accuracy and append to the list
    accuracy = accuracy_score(y_test, predictions)
    accuracy_scores.append(accuracy)

    # Define your custom loss function and calculate loss
    # Here's an example using mean squared error as a loss function
    # Replace this with your specific loss function
    loss = ((y_test - predictions) ** 2).mean()
    losses.append(loss)

# Print the accuracy scores and losses for each iteration
for i, (score, loss) in enumerate(zip(accuracy_scores, losses)):
    print(f'Iteration {i + 1} - Accuracy: {score:.2%} - Loss: {loss:.4f}')


Iteration 1 - Accuracy: 81.14% - Loss: 0.1886
Iteration 2 - Accuracy: 81.30% - Loss: 0.1870
Iteration 3 - Accuracy: 81.64% - Loss: 0.1836
Iteration 4 - Accuracy: 81.52% - Loss: 0.1848
Iteration 5 - Accuracy: 80.76% - Loss: 0.1924
Iteration 6 - Accuracy: 81.06% - Loss: 0.1894
Iteration 7 - Accuracy: 81.29% - Loss: 0.1871
Iteration 8 - Accuracy: 81.61% - Loss: 0.1839
Iteration 9 - Accuracy: 80.17% - Loss: 0.1983
Iteration 10 - Accuracy: 81.14% - Loss: 0.1886
Iteration 11 - Accuracy: 81.29% - Loss: 0.1871
Iteration 12 - Accuracy: 81.09% - Loss: 0.1891
Iteration 13 - Accuracy: 81.09% - Loss: 0.1891
Iteration 14 - Accuracy: 80.98% - Loss: 0.1902
Iteration 15 - Accuracy: 81.54% - Loss: 0.1846
Iteration 16 - Accuracy: 81.01% - Loss: 0.1899
Iteration 17 - Accuracy: 81.85% - Loss: 0.1815
Iteration 18 - Accuracy: 81.79% - Loss: 0.1821
Iteration 19 - Accuracy: 81.27% - Loss: 0.1873
Iteration 20 - Accuracy: 81.09% - Loss: 0.1891
